services:
  - type: web
    name: ad-clicker
    env: python
    plan: free
    buildCommand: "chmod +x start.sh && ./start.sh"  # 保持与网页设置一致
    startCommand: "python main.py"
    envVars:
      - key: DISPLAY
        value: ":99"
    numInstances: 15
